--- 
jobs: 
  build: 
    runs-on: ubuntu-latest
    steps: 
      - 
        uses: actions/checkout@v1
      - 
        name: "Install Node.js"
        uses: actions/setup-node@v1
        with: 
          node-version: 10.x
      - 
        name: "Install npm dependencies"
        run: "npm install"
      - 
        env: 
          SIGNING_KEY: "${{ secrets.SIGNING_KEY }}"
        name: "Decode signing keystore"
        run: "echo \"$SIGNING_KEY\" | base64 -d > android/app/signing_key.jks"
      - 
        name: "Run npm run build-android-linux"
        run: "npm run build-android-linux"
      - 
        name: "Upload compiled apk"
        uses: actions/upload-artifact@v2
        with: 
          name: Weather_Warning
          path: android\app\release\app-release.apk
name: "Build APK"
on: workflow_dispatch 
