name: Build APK
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: Install npm dependencies
      run: npm install
    - name: Run npm run build-android-linux
      run: npm run build-android-linux
    - name: Upload compiled apk
      uses: actions/upload-artifact@v2
      with:
        name: Weather_Warning.apk
        path: android/app/build/outputs/apk/release/app-release-unsigned.apk